# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.netgear_wax204: debug
    debugpy: debug

# debugpy:
#   wait: false
#   start: true
#   port: 5679
